// import { RDVButton } from "../molecules/RDVButton";
import { Menu } from "./_components/organisms/Menu";
import "./globals.css";

export const metadata = {
  title: "FionaRx",
  description: "Generated by create next app",
};

export default function RootLayout({pageTitle, children, className: additionalStyle}) {
  return (
    <html lang="fr">
      <body>
        <main className="MainLayout relative h-screen overflow-auto bg-midnight z-0">
          <Menu />
          {/* <RDVButton /> TODO: A réactiver quand je suis prête ! */}
            {children}
        </main>
      </body>
    </html>
  )
};